// detector.js
const fs = require('fs');
const path = require('path');

const apiKey = process.env.GEMINI_API_KEY;

// List of common AI-slop patterns (regexes)
const slopPatterns = [
  { name: 'delve', regex: /\bdelve(s|d|r|g)?\b/gi, suggestion: 'use "explore", "examine", or "look into"' },
  { name: 'tapestry', regex: /\btapestry\b/gi, suggestion: 'use "structure", "complex system", or "combination"' },
  { name: 'testament', regex: /\btestament\b/gi, suggestion: 'use "proof", "evidence", or "demonstration"' },
  { name: 'moreover', regex: /\bmoreover\b/gi, suggestion: 'use "also" or "in addition"' },
  { name: 'furthermore', regex: /\bfurthermore\b/gi, suggestion: 'use "also" or "next"' },
  { name: 'bespoke', regex: /\bbespoke\b/gi, suggestion: 'use "custom", "tailored", or "specific"' },
  { name: 'revolutionize', regex: /\brevolutionize(d|s|g)?\b/gi, suggestion: 'use "improve", "transform", or "change"' },
  { name: 'pivotal', regex: /\bpivotal\b/gi, suggestion: 'use "key", "important", or "critical"' },
  { name: 'throat-clearing intro', regex: /\b(in today's digital landscape|it is important to note that|in this article we will)\b/gi, suggestion: 'remove or write directly' }
];

function checkFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`Error: File not found: ${filePath}`);
    process.exit(1);
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  let totalMatches = 0;
  const reports = [];

  lines.forEach((line, idx) => {
    slopPatterns.forEach(pattern => {
      let match;
      pattern.regex.lastIndex = 0;
      while ((match = pattern.regex.exec(line)) !== null) {
        totalMatches++;
        reports.push({
          line: idx + 1,
          word: match[0],
          pattern: pattern.name,
          suggestion: pattern.suggestion,
          snippet: line.trim()
        });
      }
    });
  });

  console.log(`\n=== SLOP AUDIT REPORT: ${path.basename(filePath)} ===`);
  if (totalMatches === 0) {
    console.log('✅ No AI-slop patterns detected! Excellent writing.');
    process.exit(0);
  }

  reports.forEach(r => {
    console.log(`\nLine ${r.line}: Found "${r.word}" (Pattern: ${r.pattern})`);
    console.log(`  > Snippet: "${r.snippet}"`);
    console.log(`  > Suggestion: ${r.suggestion}`);
  });

  console.log(`\n======================================================`);
  console.log(`END: Found ${totalMatches} AI-jargon occurrences.`);
  console.log(`======================================================\n`);
  process.exit(0);
}

async function cleanFile(filePath, outputPath) {
  if (!apiKey) {
    console.error('Error: The GEMINI_API_KEY environment variable is not defined.');
    console.error('Define it by running: export GEMINI_API_KEY="your-token"');
    process.exit(1);
  }

  if (!fs.existsSync(filePath)) {
    console.error(`Error: File not found: ${filePath}`);
    process.exit(1);
  }

  const content = fs.readFileSync(filePath, 'utf8');
  console.log(`Reading ${filePath} (${content.length} characters)...`);
  console.log('Sending to Gemini for sanitization (removing AI-slop)...');

  const systemInstruction = `You are a senior copyeditor and expert in clear, concise, and natural human technical writing.
Your task is to rewrite the text provided by the user, removing any trace of "AI-slop" (artificial and repetitive jargon commonly generated by LLMs, such as "delve", "tapestry", "testament", "moreover", "furthermore", "bespoke", "revolutionize", "pivotal", and robotic transitional phrases like "in today's digital landscape", "it is important to note").
Output rules:
- Preserve the original language of the input text (if the input is in English, write in English; if it is in Portuguese, write in Portuguese).
- Maintain the exact same technical meaning and facts.
- Make the prose direct, active, and use natural, human-like vocabulary.
- Do not alter code blocks, formatting, or markdown links.
- Return ONLY the clean, rewritten text, without any explanations or introductory remarks.`;

  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [
          {
            role: 'user',
            parts: [
              { text: content }
            ]
          }
        ],
        systemInstruction: {
          parts: [
            { text: systemInstruction }
          ]
        },
        generationConfig: {
          temperature: 0.2
        }
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`API returned status ${response.status}: ${errText}`);
    }

    const data = await response.json();
    const cleanText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!cleanText) {
      throw new Error('Invalid API response format or empty output text.');
    }

    fs.writeFileSync(outputPath, cleanText, 'utf8');
    console.log(`\n[SUCCESS] Text sanitized successfully!`);
    console.log(`File saved at: ${outputPath} (${cleanText.length} characters).`);

  } catch (err) {
    console.error('Error calling Gemini API:', err.message);
    process.exit(1);
  }
}

function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (command === 'check') {
    const file = args[1];
    if (!file) {
      console.log('Usage: node detector.js check <file_path>');
      process.exit(1);
    }
    checkFile(file);
  } else if (command === 'clean') {
    const file = args[1];
    let outputIdx = args.indexOf('--output');
    let output = outputIdx !== -1 ? args[outputIdx + 1] : null;

    if (!file || !output) {
      console.log('Usage: node detector.js clean <file_path> --output <output_path>');
      process.exit(1);
    }
    cleanFile(file, output);
  } else {
    console.log('Available commands:');
    console.log('  check <file_path>                   - Scans file for AI patterns');
    console.log('  clean <file_path> --output <path>   - Sanitizes file using Gemini API');
    process.exit(1);
  }
}

main();
